### ISSUE TITLE
how to pass interval parameter when using docker container?

### ISSUE THREAD

**Issue by kingp0dd** [mpepping/solarman-mqtt#134]
Is there an environment variable for it? I'm using the docker-compose option currently.

**Comment by mpepping** [comment]
No environment variable, but what you can do in the docker compose yaml is adding the `command` parameter explicitly :

```yaml
services:
  solarman-mqtt:
    image: ghcr.io/mpepping/solarman-mqtt:main
    command: ["-d", "-i 600"]
    container_name: "solarman-mqtt"
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./config.json:/opt/app-root/src/config.json
    restart: always
```

The `-i 600` flag makes the run interval once every 10 minutes.
