### ISSUE TITLE
Option to 'retain' data

### ISSUE THREAD

**Issue by mhoogenbosch** [mpepping/solarman-mqtt#19]
Is it possible to retain data in MQTT. HA now thinks i'm still pulling 20W from the Sun when it's dark, this was the last state reported before the device went offline and got pulled to HA.

**Comment by mpepping** [comment]
Fair point. It indeed is an annoyance that there's still a small wattage reported while the PV system is offline. Even the SolarmanPV API itself reports a wattage whilst the deviceState is 'offline' (3).

I was thinking on setting the value for the wattage to 0 over MQTT when the deviceState is offline. I found it nicer not to adjust values of data reported back from the API.

For myself, I resolved this in Home Assistant for now, via an automation and a script to set entity values:

The automation: 

```yaml
alias: Reset power sensor to zero when pv is offline
trigger:
  - platform: state
    entity_id: sensor.daylight
    to: 'dawn'
condition: []
action:
  - service: python_script.set_state
    data_template:
      entity_id: sensor.solarmanpv_current_power
      state: 0
mode: single
```

The python helper script:

```python
#--------------------------------------------------------------------------------------------------
# Set the state or other attributes for the entity specified in the Automation Action
#--------------------------------------------------------------------------------------------------

# Example usage:
#
#   action:
#     service: python_script.set_state
#     data_template:
#       entity_id: Binary_sensor.sensor1
#       state: ON


inputEntity = data.get('entity_id')
inputStateObject = hass.states.get(inputEntity)
inputState = inputStateObject.state
inputAttributesObject = inputStateObject.attributes.copy()

newState = data.get('state')
if newState is not None:
    inputState = newState

newIcon = data.get('icon')
if newIcon is not None:
    inputAttributesObject['icon'] = newIcon

hass.states.set(inputEntity, inputState, inputAttributesObject)

```

That helper script is setup via the Home Assistant python_script integration (https://www.home-assistant.io/integrations/python_script/).  I just added the script to `./config/python_scripts/set_state.py`.
